### ISSUE TITLE
Maven 4.0.0 - A profile can not being actived or deactived 

### ISSUE THREAD

**Issue by khmarbaise** [khmarbaise/maven-it-extension#418]
```
java.lang.AssertionError: 
The build was not successful but was <Failure> with returnCode:<1> log file: <[ [STDOUT] Apache Maven 4.0.0-alpha-10 (89d3c0321dda868c432edf504f1884e6fd706f00)
,  [STDOUT] Maven home: /opt/hostedtoolcache/maven/4.0.0/x64
,  [STDOUT] Java version: 21.0.1, vendor: Eclipse Adoptium, runtime: /usr/lib/jvm/temurin-21-jdk-amd64
,  [STDOUT] Default locale: en, platform encoding: UTF-8
,  [STDOUT] OS name: "linux", version: "6.2.0-1018-azure", arch: "amd64", family: "unix"
,  [STDOUT] [INFO] Error stacktraces are turned on.
,  [STDOUT] [INFO] Making this build non-interactive, because the environment variable CI equals "true". Disable this detection by removing that variable or adding --force-interactive.
,  [STDOUT] [INFO] Scanning for projects...
,  [STDOUT] [ERROR] The requested profiles [unknown-profile] could not be activated or deactivated because they do not exist. -> [Help 1]
,  [STDOUT] org.apache.maven.MissingProfilesException: The requested profiles [unknown-profile] could not be activated or deactivated because they do not exist.
,  [STDOUT]     at org.apache.maven.DefaultMaven.validateRequiredProfiles(DefaultMaven.java:566)
,  [STDOUT]     at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
,  [STDOUT]     at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:228)
,  [STDOUT]     at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:153)
,  [STDOUT]     at org.apache.maven.cli.MavenCli.execute(MavenCli.java:958)
,  [STDOUT]     at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
,  [STDOUT]     at org.apache.maven.cli.MavenCli.main(MavenCli.java:205)
,  [STDOUT]     at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
,  [STDOUT]     at java.lang.reflect.Method.invoke(Method.java:580)
,  [STDOUT]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
,  [STDOUT]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
,  [STDOUT]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
,  [STDOUT]     at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
,  [STDOUT] [ERROR] 
,  [STDOUT] [ERROR] Re-run Maven using the '-X' switch to enable verbose output
,  [STDOUT] [ERROR] 
,  [STDOUT] [ERROR] For more information about the errors and possible solutions, please read the following articles:
,  [STDOUT] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProfilesException
]>
	at com.soebes.itf.examples.profiles.ProfileIT.unknown_profile(ProfileIT.java:94)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
```

**Comment by khmarbaise** [comment]
Closing it related to #421
